name: Build Workflow
on:
  push:
    branches:
      - develop
jobs:
  build_develop_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Build Website
        run: |
          npx parcel build "./src/index.html" --dist-dir "./dev" --public-url "./"
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact-develop
          path: "./dev"
  deploy_develop_artifact:
    needs: build_develop_job
    environment:
      name: development-env
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Artifacts to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact-name: build-artifact-develop
          token: ${{ secrets.GITHUB_TOKEN }}